# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ProtocolsDemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProtocolsDemoProject
  
  pod 'NVActivityIndicatorView', '~> 4.8.0'

end
